apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dotnet-role
  namespace: sincehetoldmetoo
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
