apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.appName }}
  type: {{ .Values.serviceType }}
  sessionAffinity: {{ .Values.sessionAffinity }}
  ports:
    - name: {{ .Values.ports.name }}
      protocol: {{ .Values.ports.protocol }}
      port: {{ .Values.ports.port }}
      targetPort: {{ .Values.ports.targetPort }}
