namespace: dotnetdemo

configMapName: configk8
DB_HOST: bermtec

secretName: test-secret
username: dotnetdemodocker
password: OihGX0hQxRa53/VGUXJ2Ywr3fiuOTp2lWM3DOlhMPL+ACRDKRpJJ

deploymentName: dotnetdemodeployment
replicas: 1

rollingUpdate:
  maxSurge: 25%
  maxUnavailable: 25%

appName: dotnet-app
containerName: dotnet-app
image: enariya0410/myapp:v1.0
containerPort: 5000

resources:
  requests:
    cpu: "100m"
    memory: "300Mi"
  limits:
    cpu: "200m"
    memory: "300Mi"

livenessProbe:
  initialDelaySeconds: 5
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3
  periodSeconds: 10

readinessProbe:
  initialDelaySeconds: 5
  timeoutSeconds: 2
  successThreshold: 1
  failureThreshold: 3
  periodSeconds: 10

env:  # The 'env' section for environment variables
  - name: DB_HOST
    valueFrom:
      configMapKeyRef:
        name: configk8
        key: DB_HOST
